import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { sassPlugin } from 'esbuild-sass-plugin';
import { copyFileSync, mkdirSync, existsSync, readdirSync } from 'fs';
import { join } from 'path';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [
		sassPlugin({
			type: "css",
			cssImports: true,
		}),
	],
	loader: {
		".scss": "css",
	},
});

// Separate CSS build from SCSS
const cssContext = await esbuild.context({
	entryPoints: ["src/styles/main.scss"],
	bundle: true,
	outfile: "styles.css",
	loader: {
		".scss": "css",
	},
	plugins: [
		sassPlugin({
			type: "css",
		}),
	],
	sourcemap: prod ? false : "inline",
	minify: prod,
});

// Copy assets to output directory after build
function copyAssets() {
	const assetsDir = join(process.cwd(), 'assets');
	if (existsSync(assetsDir)) {
		const files = readdirSync(assetsDir);
		for (const file of files) {
			const src = join(assetsDir, file);
			const dest = join(process.cwd(), file);
			copyFileSync(src, dest);
		}
	}
}

if (prod) {
	await context.rebuild();
	await cssContext.rebuild();
	copyAssets();
	process.exit(0);
} else {
	await context.watch();
	await cssContext.watch();
	// Copy assets initially
	copyAssets();
}
